version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/nameprep/src/it/jpms-nameprep"
      - "/saslprep/src/it/jpms-saslprep"
      - "/stringprep/src/it/jpms-stringprep"
    schedule:
      interval: "monthly"
    groups:
      all-maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-github-actions:
        patterns:
          - "*"
