version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/nameprep/src/it/jpms-nameprep"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/saslprep/src/it/jpms-saslprep"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/stringprep/src/it/jpms-stringprep"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
