name: "Lock down repository"

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          issue-comment: >
            This repository is just a mirror and does not accept bug reports,
            the primary repository is located at https://gitlab.com/ongresinc/stringprep
          skip-closed-issue-comment: true
          pr-comment: >
            This repository is just a mirror and does not accept pull requests,
            the primary repository is located at https://gitlab.com/ongresinc/stringprep
          skip-closed-pr-comment: true
